### PR TITLE
changing function calling to watsonx api

### PR DESCRIPTION
**Pull request by AnnaGutowska**
No longer requires bearer authentication

### CODE REVIEW

**Review by Erika-Russi — COMMENTED** [review]
Screenshot 2024-10-25 at 9 45 19 AM
Getting this error when I run this cell. Did you run into this @AnnaGutowska?

**Comment by AnnaGutowska** [comment]
@Erika-Russi No, I'm not facing this error on my end. Have you double checked your project id, api key, and watsonx URL? The URL is different now than in the prior version

**Comment by Erika-Russi** [comment]
> @Erika-Russi No, I'm not facing this error on my end. Have you double checked your project id, api key, and watsonx URL? The URL is different now than in the prior version

thanks, I did not set up my env variables correctly 
image

going to do a separate PR into your branch to address this.

**Comment by Erika-Russi** [comment]
@AnnaGutowska - here's my PR for this PR: https://github.com/IBM/ibmdotcom-tutorials/pull/15

**Review by Erika-Russi — APPROVED** [review]
thank you!

**Pull request merged**
