### PR TITLE
Create pixtral-multimodal-ai.ipynb

### PR DESCRIPTION
**Pull request by Erika-Russi**

### CODE REVIEW

**Review by vwinland — APPROVED** [review]
Reviewed and looks good

**Comment by AnnaGutowska** [comment]
Could you revert the langchain rag tutorial to use getpass()?

**Comment by Erika-Russi** [comment]
> Could you revert the langchain rag tutorial to use getpass()? I also can't view the file on my end. It says "Sorry, this is too big to display."

I'll use getpass for the langchain one and open a separate PR.

You'll have to pull locally to view the file @AnnaGutowska 

Also Anna - I noticed you still mention a .env file in this tutorial. We should prob remove that language so it's not confusing for anyone: https://github.com/IBM/ibmdotcom-tutorials/blob/main/generative-ai/agentic-rag.ipynb

**Comment by Erika-Russi** [comment]
Actually @AnnaGutowska - sorry for the backtracking, but I'm hesitant to change to getpass since we filmed this tutorial last week and it uses a .env file. I think it will cause some confusion if we are using getpass in the tutorial instead.

**Comment by AnnaGutowska** [comment]
I see, would you mind deleting that reference to the .env file to avoid creating a new PR for just that? I must have missed it when editing.

**Pull request merged**
